name: 'GitHub Languages Graph'
description: 'Fetches languages from all user repositories, generates a graph'
author: 'Matuyuhi'
branding:
  icon: activity
  color: green
inputs:
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'

