name: Generate Language Graph and Update README

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Languages Graph
    uses: Matuyuhi/generate-user-stat-graph-action@v0.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
